// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ready.proto

package com.gwsoft.server.game.protobuf;

public final class ReadyProtobuf {
  private ReadyProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReadyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 ready = 1;
    boolean hasReady();
    int getReady();
  }
  public static final class Ready extends
      com.google.protobuf.GeneratedMessage
      implements ReadyOrBuilder {
    // Use Ready.newBuilder() to construct.
    private Ready(Builder builder) {
      super(builder);
    }
    private Ready(boolean noInit) {}
    
    private static final Ready defaultInstance;
    public static Ready getDefaultInstance() {
      return defaultInstance;
    }
    
    public Ready getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gwsoft.server.game.protobuf.ReadyProtobuf.internal_static_Ready_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gwsoft.server.game.protobuf.ReadyProtobuf.internal_static_Ready_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 ready = 1;
    public static final int READY_FIELD_NUMBER = 1;
    private int ready_;
    public boolean hasReady() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getReady() {
      return ready_;
    }
    
    private void initFields() {
      ready_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasReady()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ready_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ready_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gwsoft.server.game.protobuf.ReadyProtobuf.ReadyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gwsoft.server.game.protobuf.ReadyProtobuf.internal_static_Ready_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gwsoft.server.game.protobuf.ReadyProtobuf.internal_static_Ready_fieldAccessorTable;
      }
      
      // Construct using com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ready_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready.getDescriptor();
      }
      
      public com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready getDefaultInstanceForType() {
        return com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready.getDefaultInstance();
      }
      
      public com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready build() {
        com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready buildPartial() {
        com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready result = new com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ready_ = ready_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready) {
          return mergeFrom((com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready other) {
        if (other == com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready.getDefaultInstance()) return this;
        if (other.hasReady()) {
          setReady(other.getReady());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasReady()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ready_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 ready = 1;
      private int ready_ ;
      public boolean hasReady() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getReady() {
        return ready_;
      }
      public Builder setReady(int value) {
        bitField0_ |= 0x00000001;
        ready_ = value;
        onChanged();
        return this;
      }
      public Builder clearReady() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ready_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Ready)
    }
    
    static {
      defaultInstance = new Ready(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Ready)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Ready_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Ready_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Ready.proto\"\026\n\005Ready\022\r\n\005ready\030\001 \002(\005B0\n" +
      "\037com.gwsoft.server.game.protobufB\rReadyP" +
      "rotobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Ready_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Ready_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Ready_descriptor,
              new java.lang.String[] { "Ready", },
              com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready.class,
              com.gwsoft.server.game.protobuf.ReadyProtobuf.Ready.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
